// Fall-Archiv des Detektivbüros Blitz: Fälle mit ZUFÄLLIGEM Täter.
// Bei jedem Start wird ein Täter ausgelost; die Spuren an den Orten werden
// passend zu seinen Merkmalen erzeugt und zufällig auf die Orte verteilt.
// Zusätzlich macht jeder Verdächtige bei der Befragung eine Zeugenaussage —
// Unschuldige sagen die Wahrheit, der Täter LÜGT (und fliegt auf, wenn die
// Lüge einer gefundenen Spur widerspricht).
// Kindgerecht: Jede Auflösung ist ein Missverständnis — kein Verbrechen.

export const CASES = [
  {
    id: "torte",
    emoji: "🎂",
    title: "Die verschwundene Riesentorte",
    tagline: "Die fünfstöckige Schulfest-Torte ist weg — eine Stunde vor dem Anschnitt!",
    intro: `Großer Auftritt für das Detektivbüro Blitz: Die berühmte <strong>fünfstöckige Schokotorte</strong> der Koch-AG ist aus der Schulküche verschwunden — eine Stunde, bevor sie beim Schulfest angeschnitten werden sollte! Auf dem Tisch: nur Krümel und ein umgekippter Sahnebecher. Untersuche die Orte, <strong>befrage</strong> die Verdächtigen (Achtung: Der Täter lügt!), prüfe Alibis — und klage an, sobald du sicher bist.`,
    orte: [
      { id: "kueche", emoji: "🍳", name: "Die Schulküche (Tatort)", flavor: "Hier stand die Torte. Der Tisch ist verschoben, eine Schublade offen." },
      { id: "flur", emoji: "🚪", name: "Der Flur vor der Küche", flavor: "Frische Spuren auf dem frisch gewischten Boden — der Täter hatte es eilig." },
      { id: "hof", emoji: "🌳", name: "Der Pausenhof", flavor: "Der Fluchtweg führt offenbar hier entlang, vorbei an den Festtischen." },
      { id: "keller", emoji: "🔦", name: "Der Vorratskeller", flavor: "Die Kellertür steht einen Spalt offen. Drinnen riecht es verdächtig nach … Schokolade?" },
      { id: "muell", emoji: "🗑️", name: "Die Mülltonnen-Ecke", flavor: "Wer etwas loswerden will, kommt hierher. Eine Tonne steht verdächtig schief." },
      { id: "buehne", emoji: "🎤", name: "Die Festbühne", flavor: "Hinter dem Vorhang könnte man prima eine Torte zwischenparken …" },
      { id: "parkplatz", emoji: "🚗", name: "Der Lehrerparkplatz", flavor: "Reifenspuren, Bollerwagen-Abdrücke — hier wird ständig etwas transportiert." },
    ],
    merkmale: [
      { id: "haar", label: "Haarfarbe", emoji: "💇", clue: (w) => `Ein Haar klebt in der Sahne — Farbe: <strong>${w}</strong>!` },
      { id: "schuh", label: "Schuhgröße", emoji: "👟", clue: (w) => `Ein Abdruck in verschüttetem Mehl — Schuhgröße: <strong>${w}</strong>.` },
      { id: "hand", label: "Händigkeit", emoji: "✋", clue: (w) => `Die Sahne-Schmierspur am Tisch zieht zur Seite — der Täter ist <strong>${w}</strong>.` },
      { id: "spur", label: "Verlorener Gegenstand", emoji: "🧩", clue: (w) => `Am Boden liegt etwas Verräterisches: <strong>${w}</strong>!` },
      { id: "duft", label: "Verräterischer Duft", emoji: "👃", clue: (w) => `Über der Stelle hängt noch ein Hauch von … <strong>${w}</strong>.` },
    ],
    verdaechtige: [
      { id: "koch", emoji: "👨‍🍳", name: "Herr Brösel", rolle: "Leiter der Koch-AG",
        werte: { haar: "grau", schuh: "44 (groß)", hand: "Rechtshänder", spur: "eine Prise Muskatnuss im Döschen", duft: "Vanille und Backofen" },
        smalltalk: "Herr Brösel poliert nervös eine Tortenspritze.",
        motiv: "Hält die Torte für „noch nicht perfekt“ — wollte sie angeblich nachbessern.",
        alibi: "Sagt, er habe die ganze Zeit am Waffelstand gestanden.",
        alibiLuege: "Am Waffelstand stand laut Plan Frau Specht — Brösel war dort nie!",
        gestaendnis: "„Die Ganache war nicht glänzend genug! Ich habe die Torte heimlich weggetragen, um sie nachzuglasieren — und dann ist mir die Zeit davongelaufen. Sie ist jetzt übrigens PERFEKT.“" },
      { id: "lena", emoji: "🎀", name: "Lena Lecker", rolle: "Schülersprecherin mit Naschschwäche",
        werte: { haar: "blond", schuh: "37 (klein)", hand: "Rechtshänder", spur: "eine Glitzer-Haarspange", duft: "Erdbeer-Kaugummi" },
        smalltalk: "Lena kaut hastig — und versteckt etwas in der Backentasche.",
        motiv: "Wurde dreimal beim Probieren der Füllung erwischt.",
        alibi: "Sagt, sie habe Luftballons an der Bühne aufgepustet.",
        alibiLuege: "Die Ballons waren schon um zwei Uhr fertig aufgehängt — lange vor der Tat!",
        gestaendnis: "„Ich wollte NUR ein Eckstück probieren! Aber dann ist mir die ganze Torte vom Wagen gerutscht und ich hab sie panisch versteckt. Das Eckstück war übrigens köstlich.“" },
      { id: "bodo", emoji: "🧹", name: "Hausmeister Bodo", rolle: "Hausmeister mit süßem Zahn",
        werte: { haar: "braun", schuh: "44 (groß)", hand: "Linkshänder", spur: "ein Schlüsselbund-Anhänger", duft: "Kaffee, schwarz, dreifach" },
        smalltalk: "Bodo lehnt am Besen und seufzt sein berühmtes Hausmeister-Seufzen.",
        motiv: "Beschwert sich seit Wochen, dass nie jemand an ihn denkt — auch nicht mit Kuchen.",
        alibi: "Sagt, er habe im Geräteraum Bierbänke gezählt.",
        alibiLuege: "Der Geräteraum war zur Tatzeit abgeschlossen — und den Schlüssel hatte die Sportlehrerin!",
        gestaendnis: "„Dreißig Jahre wische ich hier Böden, und nie kriegt der Bodo ein Stück Kuchen ab! Ich wollte die Torte nur … in Sicherheit bringen. Auf meinen Schreibtisch. Mit einer Gabel daneben.“" },
      { id: "mira", emoji: "🎨", name: "Mira Matsch", rolle: "Künstlerin der Deko-AG",
        werte: { haar: "rot", schuh: "39 (mittel)", hand: "Linkshänder", spur: "ein Klecks blaue Bastelfarbe", duft: "Farbverdünner" },
        smalltalk: "Mira mustert dich, als würde sie dein Porträt planen.",
        motiv: "Findet, die Torte ruiniere ihr Farbkonzept fürs Fest („Schokobraun! Zu MEINEM Türkis!“).",
        alibi: "Sagt, sie habe hinter der Turnhalle das Banner fertig gemalt.",
        alibiLuege: "Das Banner hängt seit dem Morgen — frische Farbe ist nirgendwo zu sehen!",
        gestaendnis: "„Braun. Neben. Türkis. Das ist ein DEKO-NOTFALL! Ich habe die Torte nur umgestellt, bis ich eine türkise Tischdecke gefunden habe. Kunst braucht Zeit!“" },
      { id: "erwin", emoji: "👴", name: "Opa Erwin", rolle: "Ehrenjuror des Backwettbewerbs",
        werte: { haar: "weiß", schuh: "42 (mittel)", hand: "Rechtshänder", spur: "eine Lesebrille mit Kordel", duft: "Hustenbonbons" },
        smalltalk: "Opa Erwin zwinkert dir zu und klopft auf seinen Jury-Ausweis.",
        motiv: "Als Juror wollte er „vorab eine kleine Qualitätskontrolle“ durchführen. Ohne Zeugen.",
        alibi: "Sagt, er habe im Liegestuhl Zeitung gelesen.",
        alibiLuege: "Seine Zeitung liegt ungelesen und zusammengerollt am Eingang — mit Adressaufkleber!",
        gestaendnis: "„Ein Juror MUSS doch vorkosten! Ich habe die Torte zur fachgerechten Prüfung beiseitegestellt. Mein Urteil übrigens: zehn von zehn Punkten. Besonders die dritte Etage.“" },
      { id: "waldi", emoji: "🐕", name: "Waldi", rolle: "Der Schulhund der 5b",
        werte: { haar: "schwarz (Fell!)", schuh: "Pfoten!", hand: "Vierbeiner", spur: "ein angeknabberter Tennisball", duft: "nasser Hund" },
        smalltalk: "Waldi legt den Kopf schief und wedelt verdächtig unschuldig.",
        motiv: "Es ist eine SCHOKOTORTE und er ist ein HUND. Mehr Motiv braucht es nicht.",
        alibi: "Lag angeblich brav schlafend im Klassenzimmer der 5b.",
        alibiLuege: "Die Tür der 5b stand offen — und sein Körbchen ist verdächtig sauber!",
        gestaendnis: "„Wuff.“ — Waldi hat die Torte stückweise unters Klettergerüst getragen. Zum Glück ist Schokolade für Hunde tabu: Er hat nur die Kirschen abgeschleckt, der Rest ist rettbar! Waldi muss zur Strafe beim Abwasch helfen (Vorwaschgang)." },
    ],
  },
  {
    id: "labor",
    emoji: "🌋",
    title: "Das Phantom im Schullabor",
    tagline: "Das Vulkan-Modell für den Wissenschaftstag ist spurlos verschwunden.",
    intro: `Morgen ist <strong>Wissenschaftstag</strong> — und heute früh war das preisgekrönte <strong>Vulkan-Modell</strong> der Forscher-AG nicht mehr im Labor! Tür verschlossen, Fenster zu … aber sechs Verdächtige hatten einen Schlüssel oder einen Weg hinein. Sichere Spuren, <strong>befrage</strong> alle (einer lügt!), prüfe Alibis — und überführe das Phantom im Labor.`,
    orte: [
      { id: "labor", emoji: "🧪", name: "Das Labor (Tatort)", flavor: "Der Tisch der Forscher-AG ist leer. Nur der Essig für den Vulkanausbruch steht noch da." },
      { id: "fenster", emoji: "🪟", name: "Die Fensterbank", flavor: "Von außen unerreichbar — aber innen ist die Blumenerde des Kaktus frisch verwühlt." },
      { id: "schrank", emoji: "🗄️", name: "Der Chemikalienschrank", flavor: "Jemand hat hier hastig etwas gesucht — die Backpulver-Dose fehlt!" },
      { id: "treppe", emoji: "🪜", name: "Das Treppenhaus", flavor: "Der schnellste Weg nach draußen. An der Wand: eine frische Schramme auf Kistenhöhe." },
      { id: "laborflur", emoji: "🏃", name: "Der Flur vor dem Labor", flavor: "Die Putzkolonne war noch nicht da — perfekt für Spurensucher." },
      { id: "bibo", emoji: "📚", name: "Die Bibliothek nebenan", flavor: "Durch die Verbindungstür könnte jemand mit sperrigem Gepäck geschlüpft sein." },
      { id: "schulhof2", emoji: "🌳", name: "Der Innenhof", flavor: "Unter dem Laborfenster blüht das Beet — und jemand ist mitten hindurchgetrampelt." },
    ],
    merkmale: [
      { id: "haar", label: "Haarfarbe", emoji: "💇", clue: (w) => `Auf dem Labortisch liegt ein Haar — Farbe: <strong>${w}</strong>!` },
      { id: "schuh", label: "Schuhwerk", emoji: "👟", clue: (w) => `Ein Abdruck in der verschütteten Kreide: <strong>${w}</strong>.` },
      { id: "hand", label: "Händigkeit", emoji: "✋", clue: (w) => `Die Wischspur an der Tafel verrät: Der Täter ist <strong>${w}</strong>.` },
      { id: "spur", label: "Verlorener Gegenstand", emoji: "🧩", clue: (w) => `Unter dem Tisch findest du: <strong>${w}</strong>!` },
      { id: "groesse", label: "Körpergröße", emoji: "📏", clue: (w) => `Die Schramme an der Wand sitzt auf einer Höhe, die zu jemandem passt, der <strong>${w}</strong> ist.` },
    ],
    verdaechtige: [
      { id: "prof", emoji: "👩‍🔬", name: "Frau Dr. Blitzschlag", rolle: "Chemielehrerin und Perfektionistin",
        werte: { haar: "schwarz", schuh: "elegante Halbschuhe", hand: "Rechtshänder", spur: "ein zerbrochener Bleistift mit Zahnabdrücken", groesse: "ziemlich groß" },
        smalltalk: "Frau Dr. Blitzschlag putzt ihre Brille exakt siebenmal.",
        motiv: "Findet, der Vulkan sei „wissenschaftlich ungenau“ — die Lava fließe unrealistisch.",
        alibi: "Sagt, sie habe im Lehrerzimmer Arbeiten korrigiert.",
        alibiLuege: "Im Lehrerzimmer war Konferenz — und auf der Anwesenheitsliste fehlt ihr Name!",
        gestaendnis: "„Die Lavafarbe war FALSCH! Echte Lava ist nicht pink! Ich habe das Modell über Nacht mitgenommen, um den Farbton zu korrigieren. Im Namen der Wissenschaft!“" },
      { id: "theo", emoji: "🤓", name: "Theo Tüftler", rolle: "Zweitplatzierter des letzten Wettbewerbs",
        werte: { haar: "rot", schuh: "Turnschuhe", hand: "Linkshänder", spur: "eine Schraube aus einem Roboterbausatz", groesse: "mittelgroß" },
        smalltalk: "Theo rechnet beim Reden leise Formeln vor sich hin.",
        motiv: "Sein Roboter verlor letztes Jahr gegen genau diesen Vulkan. Knapp. SEHR knapp.",
        alibi: "Sagt, er habe in der Bibliothek über Vulkane gelesen. Ausgerechnet.",
        alibiLuege: "Die Bibliothek hatte heute Schließtag — da hat niemand gelesen!",
        gestaendnis: "„Ich wollte ihn nur VERMESSEN, um zu beweisen, dass mein Roboter größer ist! Dann kam jemand, ich bin in Panik mit dem Vulkan unterm Arm los … Mein Roboter ist übrigens 3 cm größer. Nur fürs Protokoll.“" },
      { id: "pauline", emoji: "🧤", name: "Pauline Putzblitz", rolle: "Reinigungskraft mit Ordnungsliebe",
        werte: { haar: "blond", schuh: "Gummistiefel", hand: "Rechtshänder", spur: "ein Stück Zitronen-Putztuch", groesse: "eher klein" },
        smalltalk: "Pauline wischt beim Zuhören unsichtbare Flecken vom Türrahmen.",
        motiv: "Nennt das Modell seit Wochen „diese Staubschleuder auf Tisch drei“.",
        alibi: "Sagt, sie habe die Aula gewienert.",
        alibiLuege: "Die Aula ist staubig wie eine Wüste — da wurde seit Tagen nicht gewischt!",
        gestaendnis: "„Diese Staubschleuder hat schon wieder GEKRÜMELT! Ich habe sie nur zum Entstauben in mein Putzkämmerchen getragen. Jetzt glänzt der Vulkan übrigens wie neu. Bitte sehr.“" },
      { id: "max", emoji: "⚽", name: "Max Meter", rolle: "Torwart mit schlechtem Gewissen",
        werte: { haar: "braun", schuh: "Fußballschuhe (Stollen!)", hand: "Linkshänder", spur: "ein Stück Schienbeinschoner", groesse: "sehr groß" },
        smalltalk: "Max dribbelt nervös einen unsichtbaren Ball.",
        motiv: "Hat beim Kicken im Flur fast das Modell getroffen — und Angst, dass es wieder passiert.",
        alibi: "Sagt, er habe auf dem Sportplatz Elfmeter trainiert.",
        alibiLuege: "Der Sportplatz war wegen des Festaufbaus gesperrt — Training unmöglich!",
        gestaendnis: "„Beim Wissenschaftstag spielen wir IM FLUR das Finale! Ich hab den Vulkan in die Turnhalle getragen, damit ihm nichts passiert. Sicherheit geht vor, hat Tante Resi gesagt!“" },
      { id: "direx", emoji: "👔", name: "Direktor Donner", rolle: "Schulleiter mit Besuch vom Schulamt",
        werte: { haar: "grau", schuh: "blank polierte Lackschuhe", hand: "Linkshänder", spur: "eine goldene Krawattennadel", groesse: "ziemlich groß" },
        smalltalk: "Direktor Donner schaut dreimal auf die Uhr, bevor er antwortet.",
        motiv: "Morgen kommt das Schulamt — und der Vulkan spritzt bekanntlich Lava auf Anzüge.",
        alibi: "Sagt, er habe in seinem Büro wichtige Telefonate geführt.",
        alibiLuege: "Sein Telefon liegt seit gestern zur Reparatur beim Sekretariat — telefonieren unmöglich!",
        gestaendnis: "„Letztes Jahr traf die Lava den Inspektor MITTEN auf die Krawatte! Ich habe das Modell nur bis nach dem Besuch in meinen Schrank gesperrt. Ordnung ist die halbe Schulleitung!“" },
      { id: "hamster", emoji: "🐹", name: "Professor Knabber", rolle: "Versuchs-Hamster der Forscher-AG",
        werte: { haar: "goldbraun (Fell!)", schuh: "winzige Pfoten", hand: "Vierbeiner", spur: "ein Häufchen gehorteter Sonnenblumenkerne", groesse: "winzig (Bodenhöhe!)" },
        smalltalk: "Professor Knabber stopft sich demonstrativ die Backen voll.",
        motiv: "Sein Laufrad steht DIREKT neben dem Vulkan. Niemand fragt je den Hamster.",
        alibi: "Saß angeblich unschuldig in seinem Käfig.",
        alibiLuege: "Die Käfigtür ist offen — und im Streu liegt verdächtig viel pinke Lava-Watte!",
        gestaendnis: "„Knabber-knabber.“ — Professor Knabber hat den Vulkan Stück für Stück in seinen Käfig gezogen und als LUXUS-HÖHLE eingerichtet. Die Forscher-AG beschließt: Er darf das Watte-Stück behalten. Für die Wissenschaft." },
    ],
  },
  {
    id: "schuhe",
    emoji: "👟",
    title: "Die Glücksschuhe des Kapitäns",
    tagline: "Eine Stunde vor dem Endspiel: Die Glücksschuhe sind aus der Kabine verschwunden!",
    intro: `Heute steigt das <strong>Endspiel</strong> gegen die Adler-Schule — und Kapitänin Jule schwört auf ihre <strong>Glücksschuhe</strong> (drei Siege in Folge!). Doch der Spind ist leer. Eine Stunde bis zum Anpfiff: Sichere Spuren, <strong>befrage</strong> die Verdächtigen (der Täter lügt!), prüfe Alibis. Tick-tack, Detektiv.`,
    orte: [
      { id: "kabine", emoji: "🚪", name: "Die Umkleidekabine (Tatort)", flavor: "Jules Spind steht offen. Auf der Bank: ein feuchter Abdruck und ein Hauch von … irgendwas." },
      { id: "gang", emoji: "🏃", name: "Der Kabinengang", flavor: "Wer hier durch will, muss an der quietschenden Tür vorbei — und hinterlässt Spuren auf dem PVC." },
      { id: "platz", emoji: "🥅", name: "Der Sportplatz", flavor: "Hinter dem Tor ist der Rasen niedergetreten, als hätte da jemand etwas abgelegt … oder vergraben?" },
      { id: "waschraum", emoji: "🚿", name: "Der Waschraum", flavor: "Ein Wasserhahn tropft noch. Jemand war eben erst hier — und hat etwas abgespült." },
      { id: "tribuene", emoji: "🪑", name: "Die Tribüne", flavor: "Unter den Sitzreihen ist es dunkel und voller Verstecke. Perfekt für Schuh-Schmuggler." },
      { id: "kiosk", emoji: "🥨", name: "Der Stadion-Kiosk", flavor: "Noch geschlossen — aber an der Theke hat jemand herumhantiert." },
      { id: "busparkplatz", emoji: "🚌", name: "Der Parkplatz", flavor: "Der Adler-Mannschaftsbus parkt hier. Frische Fußspuren führen einmal drumherum." },
    ],
    merkmale: [
      { id: "haar", label: "Haarfarbe", emoji: "💇", clue: (w) => `Am Spind klebt ein Haar — Farbe: <strong>${w}</strong>!` },
      { id: "schuh", label: "Schuhgröße", emoji: "👟", clue: (w) => `Der feuchte Abdruck auf dem PVC: Größe <strong>${w}</strong>.` },
      { id: "hand", label: "Händigkeit", emoji: "✋", clue: (w) => `Der Spind wurde aufgehebelt — der Hebelansatz verrät einen <strong>${w}</strong>.` },
      { id: "spur", label: "Verlorener Gegenstand", emoji: "🧩", clue: (w) => `In der Ecke entdeckst du: <strong>${w}</strong>!` },
      { id: "geraeusch", label: "Gehörtes Geräusch", emoji: "👂", clue: (w) => `Mehrere Leute hörten zur Tatzeit dasselbe: <strong>${w}</strong>.` },
    ],
    verdaechtige: [
      { id: "ole", emoji: "🧤", name: "Ole Reserve", rolle: "Ersatztorwart, will endlich spielen",
        werte: { haar: "blond", schuh: "41", hand: "Rechtshänder", spur: "ein Torwarthandschuh-Etikett", geraeusch: "klatschende Torwarthandschuhe" },
        smalltalk: "Ole macht beim Reden Hechtsprünge nach unsichtbaren Bällen.",
        motiv: "Glaubt: Ohne Glücksschuhe spielt Jule schlecht — und ER darf endlich ran.",
        alibi: "Sagt, er habe sich am Kiosk eine Brezel geholt.",
        alibiLuege: "Der Kiosk öffnet erst zur Halbzeit — Brezel unmöglich!",
        gestaendnis: "„Ich wollte sie nur EIN Spiel lang verstecken! Einmal im Tor stehen, einmal Held sein … Ich bring sie sofort zurück. Und Jule? Du bist auch MIT Schuhen die Beste, das wollte ich nie bestreiten.“" },
      { id: "greta", emoji: "📋", name: "Greta Gegner", rolle: "Kapitänin der Adler-Schule",
        werte: { haar: "schwarz", schuh: "39", hand: "Linkshänder", spur: "ein Adler-Anstecker", geraeusch: "klackernde Stollenschuhe" },
        smalltalk: "Greta verschränkt die Arme wie vor einem Elfmeter.",
        motiv: "Drei Niederlagen gegen Jules Glücksschuhe. DREI.",
        alibi: "Sagt, sie sei mit ihrem Team noch gar nicht angereist.",
        alibiLuege: "Der Adler-Mannschaftsbus steht längst auf dem Parkplatz — Motor noch warm!",
        gestaendnis: "„Okay, OKAY! Ich habe sie versteckt — aber nur, weil ich beweisen wollte, dass ihr auch ohne Zauberschuhe gewinnt! Ehrlich gesagt … will ich einfach EINMAL ein faires Spiel auf Augenhöhe. Hier sind sie. Gutes Spiel.“" },
      { id: "resi", emoji: "☕", name: "Tante Resi", rolle: "Trainerin mit Geheimnissen",
        werte: { haar: "grau", schuh: "38", hand: "Rechtshänder", spur: "ein Teebeutel-Anhänger (Kamille)", geraeusch: "klimperndes Teegeschirr" },
        smalltalk: "Tante Resi rührt bedeutungsvoll in einer leeren Tasse.",
        motiv: "Murmelte gestern: „Diese Schuhe sind durchgelatscht — ein Sicherheitsrisiko!“",
        alibi: "Sagt, sie habe in der Küche Halbzeit-Tee gekocht.",
        alibiLuege: "Der Wasserkocher in der Küche ist eiskalt — da wurde nichts gekocht!",
        gestaendnis: "„Die Sohle war LOSE, Kindchen! Ich habe sie heimlich zum Schuster-Express gebracht — sie sollten VOR dem Anpfiff zurück sein. Überraschung misslungen, Schuhe aber repariert. Und jetzt: Tee.“" },
      { id: "kalle", emoji: "🛒", name: "Kalle Sammler", rolle: "Fan und Sammler von Vereins-Andenken",
        werte: { haar: "rot", schuh: "44", hand: "Linkshänder", spur: "ein Sammelalbum-Sticker", geraeusch: "raschelndes Albumpapier" },
        smalltalk: "Kalle blättert hektisch in seinem Sammelalbum.",
        motiv: "Sein Sammelalbum hat genau EINE Lücke: „Legendäre Schuhe“.",
        alibi: "Sagt, er habe am Eingang Programmhefte verteilt.",
        alibiLuege: "Die Programmhefte liegen unangetastet im Karton — verteilt hat sie niemand!",
        gestaendnis: "„Ich wollte sie nur FOTOGRAFIEREN! Für das Album! Aber dann kam jemand, und ich bin mit den Schuhen hinterm Tor in Deckung … Hier, bitte. Krieg ich trotzdem ein Autogramm auf die Sohle?“" },
      { id: "timmy", emoji: "🧒", name: "Timmy", rolle: "Jules kleiner Bruder und größter Fan",
        werte: { haar: "braun", schuh: "33 (winzig)", hand: "Linkshänder", spur: "ein Lutscher-Stiel", geraeusch: "piepsende Blink-Turnschuhe" },
        smalltalk: "Timmy schaut dich mit seinen größten Unschuldsaugen an.",
        motiv: "Will einmal „in den Schuhen einer Legende“ aufs Tor schießen. Sie sind ihm nur acht Nummern zu groß.",
        alibi: "Sagt, er habe vorne am Eingang Fähnchen geschwenkt.",
        alibiLuege: "Die Fähnchen werden erst zum Einlauf verteilt — die Kiste ist noch zugeklebt!",
        gestaendnis: "„Ich wollte EINMAL wie Jule sein! Ich bin in den Riesenschuhen bis zum Elfmeterpunkt gestakst — dann bin ich umgefallen und hab sie unter der Tribüne versteckt, damit keiner lacht. Sorry, Jule. Du bist die Beste.“" },
      { id: "socke", emoji: "🐈", name: "Socke", rolle: "Die Sportplatz-Katze",
        werte: { haar: "getigert (Fell!)", schuh: "Samtpfoten", hand: "Vierbeiner", spur: "eine ausgerupfte Schnürsenkel-Quaste", geraeusch: "leises, sehr zufriedenes Schnurren" },
        smalltalk: "Socke blinzelt langsam. Das kann alles oder nichts bedeuten.",
        motiv: "Baumelnde Schnürsenkel. Eine Katze. Das Universum hatte keine Wahl.",
        alibi: "Döste angeblich auf der Trainerbank in der Sonne.",
        alibiLuege: "Die Trainerbank ist klatschnass vom Rasensprenger — da döst keine Katze!",
        gestaendnis: "„Miau.“ — Socke hat die Schuhe an den Schnürsenkeln unter die Tribüne gezerrt. Dort liegen sie: unversehrt, mit drei neuen Kratz-Autogrammen. Socke wird zur offiziellen Maskottchen-Katze befördert." },
    ],
  },
];

// Generische Texte für Sonder-Orte (werden zufällig vergeben)
export const BONUS_TEXT = "Zwischen den Spuren liegt ein <strong>verlorenes Ermittler-Notizbuch</strong> mit Geheimtipps zur Alibi-Prüfung — das verschafft dir eine <strong>zusätzliche Alibi-Prüfung</strong>! (+1)";
export const NIETEN = [
  "Hier gibt es … ein versteinertes Pausenbrot. Es schweigt beharrlich.",
  "Nur eine Spinne. Sie verweigert die Aussage und webt weiter.",
  "Ein einsamer, linker Handschuh. Seit Jahren vermisst — aber nicht von deinem Täter.",
  "Drei Kaugummipapierchen von 1998. Kalt, älteste Spur der Welt.",
  "Ein vergilbter Zettel: „Bin gleich zurück — B.“ Hilft dir exakt null weiter.",
];
