// Fall-Archiv des Detektivbüros Blitz: Fälle mit ZUFÄLLIGEM Täter.
// Bei jedem Start wird ein Täter ausgelost; die Spuren an den Orten
// werden passend zu seinen Merkmalen erzeugt. Wichtig (kindgerecht):
// Jede Auflösung ist ein Missverständnis oder eine Dummheit — kein Verbrechen.
//
// Damit jeder Fall lösbar ist: Die Merkmal-Kombination jedes Verdächtigen
// ist einzigartig (wird vom Validierungsskript geprüft).

export const CASES = [
  {
    id: "torte",
    emoji: "🎂",
    title: "Die verschwundene Riesentorte",
    tagline: "Die fünfstöckige Schulfest-Torte ist weg — eine Stunde vor dem Anschnitt!",
    intro: `Großer Auftritt für das Detektivbüro Blitz: Die berühmte <strong>fünfstöckige Schokotorte</strong> der Koch-AG ist aus der Schulküche verschwunden — eine Stunde, bevor sie beim Schulfest angeschnitten werden sollte! Auf dem Tisch: nur noch Krümel und ein umgekippter Sahnebecher. Finde heraus, wer die Torte hat. Untersuche Orte, vergleiche die Steckbriefe — und klage an, sobald du dir sicher bist.`,
    orte: [
      { id: "kueche", emoji: "🍳", name: "Die Schulküche (Tatort)", flavor: "Hier stand die Torte. Der Tisch ist verschoben, eine Schublade offen." },
      { id: "flur", emoji: "🚪", name: "Der Flur vor der Küche", flavor: "Frische Spuren auf dem frisch gewischten Boden — der Täter hatte es eilig." },
      { id: "hof", emoji: "🌳", name: "Der Pausenhof", flavor: "Der Fluchtweg führt offenbar hier entlang, vorbei an den Festtischen." },
      { id: "keller", emoji: "🔦", name: "Der Vorratskeller", flavor: "Die Kellertür steht einen Spalt offen. Drinnen riecht es verdächtig nach … Schokolade?" },
    ],
    merkmale: [
      { id: "haar", label: "Haarfarbe", emoji: "💇", clue: (w) => `Ein Haar klebt in der Sahne — Farbe: <strong>${w}</strong>!` },
      { id: "schuh", label: "Schuhgröße", emoji: "👟", clue: (w) => `Ein Abdruck in verschüttetem Mehl — Schuhgröße: <strong>${w}</strong>.` },
      { id: "hand", label: "Händigkeit", emoji: "✋", clue: (w) => `Die Sahne-Schmierspur am Tisch zieht zur Seite — der Täter ist <strong>${w}</strong>.` },
      { id: "spur", label: "Besondere Spur", emoji: "🧩", clue: (w) => `Daneben liegt etwas Verräterisches: <strong>${w}</strong>!` },
    ],
    verdaechtige: [
      { id: "koch", emoji: "👨‍🍳", name: "Herr Brösel", rolle: "Leiter der Koch-AG",
        werte: { haar: "grau", schuh: "44 (groß)", hand: "Rechtshänder", spur: "eine Prise Muskatnuss" },
        motiv: "Hält die Torte für „noch nicht perfekt“ — wollte sie angeblich nachbessern.",
        alibi: "Sagt, er habe die ganze Zeit am Waffelstand gestanden.",
        alibiLuege: "Am Waffelstand stand aber laut Plan Frau Specht — Brösel war dort nie!",
        gestaendnis: "„Die Ganache war nicht glänzend genug! Ich habe die Torte in den Keller getragen, um sie nachzuglasieren — und dann ist mir die Zeit davongelaufen. Sie ist jetzt übrigens PERFEKT.“" },
      { id: "lena", emoji: "🎀", name: "Lena Lecker", rolle: "Schülersprecherin mit Naschschwäche",
        werte: { haar: "blond", schuh: "37 (klein)", hand: "Rechtshänder", spur: "eine Glitzer-Haarspange" },
        motiv: "Wurde dreimal beim Probieren der Füllung erwischt.",
        alibi: "Sagt, sie habe Luftballons an der Bühne aufgepustet.",
        alibiLuege: "Die Ballons waren schon um zwei Uhr fertig aufgehängt — lange vor der Tat!",
        gestaendnis: "„Ich wollte NUR ein Eckstück probieren! Aber dann ist mir die ganze Torte vom Wagen gerutscht und ich hab sie panisch versteckt. Das Eckstück war übrigens köstlich.“" },
      { id: "bodo", emoji: "🧹", name: "Hausmeister Bodo", rolle: "Hausmeister mit süßem Zahn",
        werte: { haar: "braun", schuh: "44 (groß)", hand: "Linkshänder", spur: "ein Schlüsselbund-Anhänger" },
        motiv: "Beschwert sich seit Wochen, dass nie jemand an ihn denkt — auch nicht mit Kuchen.",
        alibi: "Sagt, er habe im Geräteraum Bierbänke gezählt.",
        alibiLuege: "Der Geräteraum war zur Tatzeit abgeschlossen — und den Schlüssel hatte die Sportlehrerin!",
        gestaendnis: "„Dreißig Jahre wische ich hier Böden, und nie kriegt der Bodo ein Stück Kuchen ab! Ich wollte die Torte nur … in Sicherheit bringen. Auf meinen Schreibtisch. Mit einer Gabel daneben.“" },
      { id: "mira", emoji: "🎨", name: "Mira Matsch", rolle: "Künstlerin der Deko-AG",
        werte: { haar: "rot", schuh: "39 (mittel)", hand: "Linkshänder", spur: "ein Klecks blaue Bastelfarbe" },
        motiv: "Findet, die Torte ruiniere ihr Farbkonzept fürs Fest („Schokobraun! Zu MEINEM Türkis!“).",
        alibi: "Sagt, sie habe hinter der Turnhalle das Banner fertig gemalt.",
        alibiLuege: "Das Banner hängt seit dem Morgen — frische Farbe ist nirgendwo zu sehen!",
        gestaendnis: "„Braun. Neben. Türkis. Das ist ein DEKO-NOTFALL! Ich habe die Torte nur umgestellt, bis ich eine türkise Tischdecke gefunden habe. Kunst braucht Zeit!“" },
      { id: "waldi", emoji: "🐕", name: "Waldi", rolle: "Der Schulhund der 5b",
        werte: { haar: "schwarz (Fell!)", schuh: "Pfoten!", hand: "Vierbeiner", spur: "ein angeknabberter Tennisball" },
        motiv: "Es ist eine SCHOKOTORTE und er ist ein HUND. Mehr Motiv braucht es nicht.",
        alibi: "Lag angeblich brav schlafend im Klassenzimmer der 5b.",
        alibiLuege: "Die Tür der 5b stand offen — und sein Körbchen ist verdächtig sauber!",
        gestaendnis: "„Wuff.“ — Waldi hat die Torte stückweise unters Klettergerüst getragen. Zum Glück ist Schokolade für Hunde tabu: Er hat nur die Kirschen abgeschleckt, der Rest ist rettbar! Waldi muss zur Strafe beim Abwasch helfen (Vorwaschgang)." },
    ],
  },
  {
    id: "labor",
    emoji: "🌋",
    title: "Das Phantom im Schullabor",
    tagline: "Das Vulkan-Modell für den Wissenschaftstag ist spurlos verschwunden.",
    intro: `Morgen ist <strong>Wissenschaftstag</strong> — und heute früh war das preisgekrönte <strong>Vulkan-Modell</strong> der Forscher-AG nicht mehr im Labor! Das Fenster war zu, die Tür verschlossen … aber vier Personen (und ein sehr kluger Versuchs-Hamster) hatten einen Schlüssel oder einen Weg hinein. Sichere Spuren, prüfe Alibis und finde das Phantom im Labor.`,
    orte: [
      { id: "labor", emoji: "🧪", name: "Das Labor (Tatort)", flavor: "Der Tisch der Forscher-AG ist leer. Nur der Essig für den Vulkanausbruch steht noch da." },
      { id: "fenster", emoji: "🪟", name: "Die Fensterbank", flavor: "Von außen unerreichbar — aber innen ist die Blumenerde des Kaktus frisch verwühlt." },
      { id: "schrank", emoji: "🗄️", name: "Der Chemikalienschrank", flavor: "Jemand hat hier hastig etwas gesucht — die Backpulver-Dose fehlt!" },
      { id: "treppe", emoji: "🪜", name: "Das Treppenhaus", flavor: "Der schnellste Weg nach draußen. An der Wand: eine frische Schramme auf Kistenhöhe." },
    ],
    merkmale: [
      { id: "haar", label: "Haarfarbe", emoji: "💇", clue: (w) => `Auf dem Labortisch liegt ein Haar — Farbe: <strong>${w}</strong>!` },
      { id: "schuh", label: "Schuhwerk", emoji: "👟", clue: (w) => `Ein Abdruck in der verschütteten Kreide: <strong>${w}</strong>.` },
      { id: "hand", label: "Händigkeit", emoji: "✋", clue: (w) => `Der Kreidestrich an der Tafel wurde von einem <strong>${w}</strong> gewischt — die Wischrichtung verrät es.` },
      { id: "spur", label: "Besondere Spur", emoji: "🧩", clue: (w) => `Unter dem Tisch findest du: <strong>${w}</strong>!` },
    ],
    verdaechtige: [
      { id: "prof", emoji: "👩‍🔬", name: "Frau Dr. Blitzschlag", rolle: "Chemielehrerin und Perfektionistin",
        werte: { haar: "schwarz", schuh: "elegante Halbschuhe", hand: "Rechtshänder", spur: "ein zerbrochener Bleistift mit Zahnabdrücken" },
        motiv: "Findet, der Vulkan sei „wissenschaftlich ungenau“ — die Lava fließe unrealistisch.",
        alibi: "Sagt, sie habe im Lehrerzimmer Arbeiten korrigiert.",
        alibiLuege: "Im Lehrerzimmer war Konferenz — und auf der Anwesenheitsliste fehlt ihr Name!",
        gestaendnis: "„Die Lavafarbe war FALSCH! Echte Lava ist nicht pink! Ich habe das Modell über Nacht mitgenommen, um den Farbton zu korrigieren. Im Namen der Wissenschaft!“" },
      { id: "theo", emoji: "🤓", name: "Theo Tüftler", rolle: "Zweitplatzierter des letzten Wettbewerbs",
        werte: { haar: "rot", schuh: "Turnschuhe", hand: "Linkshänder", spur: "eine Schraube aus einem Roboterbausatz" },
        motiv: "Sein Roboter verlor letztes Jahr gegen genau diesen Vulkan. Knapp. SEHR knapp.",
        alibi: "Sagt, er habe in der Bibliothek über Vulkane gelesen. Ausgerechnet.",
        alibiLuege: "Die Bibliothek hatte heute Schließtag — da hat niemand gelesen!",
        gestaendnis: "„Ich wollte ihn nur VERMESSEN, um zu beweisen, dass mein Roboter größer ist! Dann kam jemand, ich bin in Panik mit dem Vulkan unterm Arm los … Mein Roboter ist übrigens 3 cm größer. Nur fürs Protokoll.“" },
      { id: "pauline", emoji: "🧤", name: "Pauline Putzblitz", rolle: "Reinigungskraft mit Ordnungsliebe",
        werte: { haar: "blond", schuh: "Gummistiefel", hand: "Rechtshänder", spur: "ein Stück Zitronen-Putztuch" },
        motiv: "Nennt das Modell seit Wochen „diese Staubschleuder auf Tisch drei“.",
        alibi: "Sagt, sie habe die Aula gewienert.",
        alibiLuege: "Die Aula ist staubig wie eine Wüste — da wurde seit Tagen nicht gewischt!",
        gestaendnis: "„Diese Staubschleuder hat schon wieder GEKRÜMELT! Ich habe sie nur zum Entstauben in mein Putzkämmerchen getragen. Jetzt glänzt der Vulkan übrigens wie neu. Bitte sehr.“" },
      { id: "max", emoji: "⚽", name: "Max Meter", rolle: "Torwart mit schlechtem Gewissen",
        werte: { haar: "braun", schuh: "Fußballschuhe (Stollen!)", hand: "Linkshänder", spur: "ein Stück Schienbeinschoner" },
        motiv: "Hat beim Kicken im Flur fast das Modell getroffen — und Angst, dass es beim Fest wieder passiert.",
        alibi: "Sagt, er habe auf dem Sportplatz Elfmeter trainiert.",
        alibiLuege: "Der Sportplatz war wegen des Festaufbaus gesperrt — Training unmöglich!",
        gestaendnis: "„Beim Wissenschaftstag spielen wir IM FLUR das Finale! Ich hab den Vulkan in die Turnhalle getragen, damit ihm nichts passiert. Sicherheit geht vor, hat Tante Resi gesagt!“" },
      { id: "hamster", emoji: "🐹", name: "Professor Knabber", rolle: "Versuchs-Hamster der Forscher-AG",
        werte: { haar: "goldbraun (Fell!)", schuh: "winzige Pfoten", hand: "Vierbeiner", spur: "ein Häufchen gehorteter Sonnenblumenkerne" },
        motiv: "Sein Laufrad steht DIREKT neben dem Vulkan. Niemand fragt je den Hamster.",
        alibi: "Saß angeblich unschuldig in seinem Käfig.",
        alibiLuege: "Die Käfigtür ist offen — und im Streu liegt verdächtig viel pinke Lava-Watte!",
        gestaendnis: "„Knabber-knabber.“ — Professor Knabber hat den Vulkan Stück für Stück in seinen Käfig gezogen und als LUXUS-HÖHLE eingerichtet. Die Forscher-AG beschließt: Er darf das Watte-Stück behalten. Für die Wissenschaft." },
    ],
  },
  {
    id: "schuhe",
    emoji: "👟",
    title: "Die Glücksschuhe des Kapitäns",
    tagline: "Eine Stunde vor dem Endspiel: Die Glücksschuhe sind aus der Kabine verschwunden!",
    intro: `Heute steigt das <strong>Endspiel</strong> gegen die Adler-Schule — und Kapitänin Jule schwört auf ihre <strong>Glücksschuhe</strong> (drei Siege in Folge!). Doch die Kabine ist leer: Die Schuhe sind weg, nur die Schnürsenkel-Verpackung liegt noch da. Eine Stunde bis zum Anpfiff, Detektiv. Tick-tack.`,
    orte: [
      { id: "kabine", emoji: "🚪", name: "Die Umkleidekabine (Tatort)", flavor: "Jules Spind steht offen. Auf der Bank: ein feuchter Abdruck und der Duft von … Pfefferminz?" },
      { id: "gang", emoji: "🏃", name: "Der Kabinengang", flavor: "Wer hier durch will, muss an der quietschenden Tür vorbei — und hinterlässt Spuren auf dem PVC." },
      { id: "platz", emoji: "🥅", name: "Der Sportplatz", flavor: "Hinter dem Tor ist der Rasen niedergetreten, als hätte da jemand etwas abgelegt … oder vergraben?" },
      { id: "waschraum", emoji: "🚿", name: "Der Waschraum", flavor: "Ein Wasserhahn tropft noch. Jemand war eben erst hier — und hat etwas abgespült." },
    ],
    merkmale: [
      { id: "haar", label: "Haarfarbe", emoji: "💇", clue: (w) => `Am Spind klebt ein Haar — Farbe: <strong>${w}</strong>!` },
      { id: "schuh", label: "Schuhgröße", emoji: "👟", clue: (w) => `Der feuchte Abdruck auf dem PVC: Größe <strong>${w}</strong>.` },
      { id: "hand", label: "Händigkeit", emoji: "✋", clue: (w) => `Der Spind wurde aufgehebelt — der Hebelansatz verrät einen <strong>${w}</strong>.` },
      { id: "spur", label: "Besondere Spur", emoji: "🧩", clue: (w) => `In der Ecke entdeckst du: <strong>${w}</strong>!` },
    ],
    verdaechtige: [
      { id: "ole", emoji: "🧤", name: "Ole Reserve", rolle: "Ersatztorwart, will endlich spielen",
        werte: { haar: "blond", schuh: "41", hand: "Rechtshänder", spur: "ein Torwarthandschuh-Etikett" },
        motiv: "Glaubt: Ohne Glücksschuhe spielt Jule schlecht — und ER darf endlich ran.",
        alibi: "Sagt, er habe sich am Kiosk eine Brezel geholt.",
        alibiLuege: "Der Kiosk öffnet erst zur Halbzeit — Brezel unmöglich!",
        gestaendnis: "„Ich wollte sie nur EIN Spiel lang verstecken! Einmal im Tor stehen, einmal Held sein … Ich bring sie sofort zurück. Und Jule? Du bist auch MIT Schuhen die Beste, das wollte ich nie bestreiten.“" },
      { id: "greta", emoji: "📋", name: "Greta Gegner", rolle: "Kapitänin der Adler-Schule",
        werte: { haar: "schwarz", schuh: "39", hand: "Linkshänder", spur: "ein Adler-Anstecker" },
        motiv: "Drei Niederlagen gegen Jules Glücksschuhe. DREI.",
        alibi: "Sagt, sie sei mit ihrem Team noch gar nicht angereist.",
        alibiLuege: "Der Adler-Mannschaftsbus steht längst auf dem Parkplatz — Motor noch warm!",
        gestaendnis: "„Okay, OKAY! Ich habe sie versteckt — aber nur, weil ich beweisen wollte, dass ihr auch ohne Zauberschuhe gewinnt! Ehrlich gesagt … will ich einfach EINMAL ein faires Spiel auf Augenhöhe. Hier sind sie. Gutes Spiel.“" },
      { id: "resi", emoji: "☕", name: "Tante Resi", rolle: "Trainerin mit Geheimnissen",
        werte: { haar: "grau", schuh: "38", hand: "Rechtshänder", spur: "ein Teebeutel-Anhänger (Kamille)" },
        motiv: "Murmelte gestern: „Diese Schuhe sind durchgelatscht — ein Sicherheitsrisiko!“",
        alibi: "Sagt, sie habe in der Küche Halbzeit-Tee gekocht.",
        alibiLuege: "Der Wasserkocher in der Küche ist eiskalt — da wurde nichts gekocht!",
        gestaendnis: "„Die Sohle war LOSE, Kindchen! Ich habe sie heimlich zum Schuster-Express gebracht — sie sollten VOR dem Anpfiff zurück sein. Überraschung misslungen, Schuhe aber repariert. Und jetzt: Tee.“" },
      { id: "kalle", emoji: "🛒", name: "Kalle Sammler", rolle: "Fan und Sammler von Vereins-Andenken",
        werte: { haar: "rot", schuh: "44", hand: "Linkshänder", spur: "ein Sammelalbum-Sticker" },
        motiv: "Sein Sammelalbum hat genau EINE Lücke: „Legendäre Schuhe“.",
        alibi: "Sagt, er habe am Eingang Programmhefte verteilt.",
        alibiLuege: "Die Programmhefte liegen unangetastet im Karton — verteilt hat sie niemand!",
        gestaendnis: "„Ich wollte sie nur FOTOGRAFIEREN! Für das Album! Aber dann kam jemand, und ich bin mit den Schuhen hinterm Tor in Deckung … Hier, bitte. Krieg ich trotzdem ein Autogramm auf die Sohle?“" },
      { id: "socke", emoji: "🐈", name: "Socke", rolle: "Die Sportplatz-Katze",
        werte: { haar: "getigert (Fell!)", schuh: "Samtpfoten", hand: "Vierbeiner", spur: "eine ausgerupfte Schnürsenkel-Quaste" },
        motiv: "Baumelnde Schnürsenkel. Eine Katze. Das Universum hatte keine Wahl.",
        alibi: "Döste angeblich auf der Trainerbank in der Sonne.",
        alibiLuege: "Die Trainerbank ist klatschnass vom Rasensprenger — da döst keine Katze!",
        gestaendnis: "„Miau.“ — Socke hat die Schuhe an den Schnürsenkeln unter die Tribüne gezerrt. Dort liegen sie: unversehrt, mit drei neuen Kratz-Autogrammen. Socke wird zur offiziellen Maskottchen-Katze befördert." },
    ],
  },
];
